tests: audio_module: Fix compiler warnings
Using memcpy to copy strings which are shorter than the requested copy
length gives compiler warnings about exceeding array bounds, for
instance:

  error: 'memcpy' forming offset 19 is out of the bounds [0, 19]

Therefore, use strncpy() instead.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>