cmake: modules: conditional sourcing of Kconfig for NCS extended modules
nRF Connect SDK may extend Kconfig files for Zephyr modules.
Extending Kconfig files located outside of sdk-nrf or Zephyr may contain
dependencies to Kconfig symbol in the external repo.

This creates a hard dependency to such repo, resulting in errors if
nRF Connect SDK downstream users tries to remove such project from their
downstream manifest.
> warning: <SETTING> (defined at Kconfig:<n>) defined with type unknown
>
> warning: <SETTING> (defined at Kconfig:<n>) defined without a prompt
>
> error: Aborting due to Kconfig warnings

This commit introduces a principle for only sourcing nRF Connect SDK
module extensions when the external module Kconfig is available.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>